PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/vndk-26-arm32/android.frameworks.displayservice@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.frameworks.displayservice@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.frameworks.schedulerservice@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.frameworks.schedulerservice@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.frameworks.sensorservice@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.frameworks.sensorservice@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.frameworks.vr.composer@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.frameworks.vr.composer@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.audio@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.audio@2.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.audio.common@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.audio.common@2.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.audio.common@2.0-util.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.audio.common@2.0-util.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.audio.effect@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.audio.effect@2.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.automotive.evs@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.automotive.evs@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.automotive.vehicle@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.automotive.vehicle@2.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.biometrics.fingerprint@2.1.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.biometrics.fingerprint@2.1.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.bluetooth@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.bluetooth@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.boot@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.boot@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.broadcastradio@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.broadcastradio@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.broadcastradio@1.1.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.broadcastradio@1.1.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.camera.common@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.camera.common@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.camera.device@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.camera.device@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.camera.device@3.2.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.camera.device@3.2.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.camera.metadata@3.2.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.camera.metadata@3.2.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.camera.provider@2.4.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.camera.provider@2.4.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.configstore@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.configstore@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.configstore-utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.configstore-utils.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.contexthub@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.contexthub@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.drm@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.drm@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.dumpstate@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.dumpstate@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.gatekeeper@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.gatekeeper@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.gnss@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.gnss@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.graphics.allocator@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.graphics.allocator@2.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.graphics.bufferqueue@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.graphics.bufferqueue@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.graphics.composer@2.1.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.graphics.composer@2.1.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.health@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.health@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.ir@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.ir@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.keymaster@3.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.keymaster@3.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.light@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.light@2.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.media@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.media@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.media.omx@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.media.omx@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.memtrack@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.memtrack@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.nfc@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.nfc@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.power@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.power@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.radio@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.radio@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.radio.deprecated@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.radio.deprecated@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.sensors@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.sensors@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.soundtrigger@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.soundtrigger@2.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.tetheroffload.config@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.tetheroffload.config@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.tetheroffload.control@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.tetheroffload.control@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.thermal@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.thermal@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.tv.cec@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.tv.cec@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.tv.input@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.tv.input@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.usb@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.usb@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.vibrator@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.vibrator@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.vr@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.vr@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.wifi@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.wifi@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hardware.wifi.supplicant@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hardware.wifi.supplicant@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hidl.allocator@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hidl.allocator@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hidl.base@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hidl.base@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hidl.token@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hidl.token@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.hidl.token@1.0-utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.hidl.token@1.0-utils.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.system.net.netd@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.system.net.netd@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/android.system.wifi.keystore@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/android.system.wifi.keystore@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/libandroidfw.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libandroidfw.so \
	$(LOCAL_PATH)/vndk-26-arm32/libandroid_runtime.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libandroid_runtime.so \
	$(LOCAL_PATH)/vndk-26-arm32/libandroid.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libandroid.so \
	$(LOCAL_PATH)/vndk-26-arm32/libappfuse.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libappfuse.so \
	$(LOCAL_PATH)/vndk-26-arm32/libaudioclient.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libaudioclient.so \
	$(LOCAL_PATH)/vndk-26-arm32/libaudiomanager.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libaudiomanager.so \
	$(LOCAL_PATH)/vndk-26-arm32/libaudioroute.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libaudioroute.so \
	$(LOCAL_PATH)/vndk-26-arm32/libaudioutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libaudioutils.so \
	$(LOCAL_PATH)/vndk-26-arm32/libavservices_minijail.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libavservices_minijail.so \
	$(LOCAL_PATH)/vndk-26-arm32/libbinder.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libbinder.so \
	$(LOCAL_PATH)/vndk-26-arm32/libcamera2ndk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libcamera2ndk.so \
	$(LOCAL_PATH)/vndk-26-arm32/libcamera_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libcamera_client.so \
	$(LOCAL_PATH)/vndk-26-arm32/libcamera_metadata.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libcamera_metadata.so \
	$(LOCAL_PATH)/vndk-26-arm32/libcameraservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libcameraservice.so \
	$(LOCAL_PATH)/vndk-26-arm32/libcap.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libcap.so \
	$(LOCAL_PATH)/vndk-26-arm32/libcrypto.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libcrypto.so \
	$(LOCAL_PATH)/vndk-26-arm32/libcrypto_utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libcrypto_utils.so \
	$(LOCAL_PATH)/vndk-26-arm32/libcurl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libcurl.so \
	$(LOCAL_PATH)/vndk-26-arm32/libdebuggerd_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libdebuggerd_client.so \
	$(LOCAL_PATH)/vndk-26-arm32/libdiskconfig.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libdiskconfig.so \
	$(LOCAL_PATH)/vndk-26-arm32/libdng_sdk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libdng_sdk.so \
	$(LOCAL_PATH)/vndk-26-arm32/libdumpstateutil.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libdumpstateutil.so \
	$(LOCAL_PATH)/vndk-26-arm32/libEGL.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libEGL.so \
	$(LOCAL_PATH)/vndk-26-arm32/libETC1.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libETC1.so \
	$(LOCAL_PATH)/vndk-26-arm32/libevent.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libevent.so \
	$(LOCAL_PATH)/vndk-26-arm32/libexif.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libexif.so \
	$(LOCAL_PATH)/vndk-26-arm32/libexpat.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libexpat.so \
	$(LOCAL_PATH)/vndk-26-arm32/libfmq.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libfmq.so \
	$(LOCAL_PATH)/vndk-26-arm32/libgatekeeper.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libgatekeeper.so \
	$(LOCAL_PATH)/vndk-26-arm32/libgui.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libgui.so \
	$(LOCAL_PATH)/vndk-26-arm32/libhardware_legacy.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libhardware_legacy.so \
	$(LOCAL_PATH)/vndk-26-arm32/libharfbuzz_ng.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libharfbuzz_ng.so \
	$(LOCAL_PATH)/vndk-26-arm32/libhwui.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libhwui.so \
	$(LOCAL_PATH)/vndk-26-arm32/libicui18n.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libicui18n.so \
	$(LOCAL_PATH)/vndk-26-arm32/libicuuc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libicuuc.so \
	$(LOCAL_PATH)/vndk-26-arm32/libimg_utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libimg_utils.so \
	$(LOCAL_PATH)/vndk-26-arm32/libinput.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libinput.so \
	$(LOCAL_PATH)/vndk-26-arm32/libjavacore.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libjavacore.so \
	$(LOCAL_PATH)/vndk-26-arm32/libjnigraphics.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libjnigraphics.so \
	$(LOCAL_PATH)/vndk-26-arm32/libjpeg.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libjpeg.so \
	$(LOCAL_PATH)/vndk-26-arm32/libkeymaster1.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libkeymaster1.so \
	$(LOCAL_PATH)/vndk-26-arm32/libkeymaster_messages.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libkeymaster_messages.so \
	$(LOCAL_PATH)/vndk-26-arm32/libkeystore_binder.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libkeystore_binder.so \
	$(LOCAL_PATH)/vndk-26-arm32/libldacBT_abr.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libldacBT_abr.so \
	$(LOCAL_PATH)/vndk-26-arm32/libldacBT_enc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libldacBT_enc.so \
	$(LOCAL_PATH)/vndk-26-arm32/liblz4.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/liblz4.so \
	$(LOCAL_PATH)/vndk-26-arm32/libmediacodecservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libmediacodecservice.so \
	$(LOCAL_PATH)/vndk-26-arm32/libmediadrm.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libmediadrm.so \
	$(LOCAL_PATH)/vndk-26-arm32/libmedia_helper.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libmedia_helper.so \
	$(LOCAL_PATH)/vndk-26-arm32/libmediametrics.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libmediametrics.so \
	$(LOCAL_PATH)/vndk-26-arm32/libmedia.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libmedia.so \
	$(LOCAL_PATH)/vndk-26-arm32/libmediautils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libmediautils.so \
	$(LOCAL_PATH)/vndk-26-arm32/libmemtrack.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libmemtrack.so \
	$(LOCAL_PATH)/vndk-26-arm32/libmemunreachable.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libmemunreachable.so \
	$(LOCAL_PATH)/vndk-26-arm32/libminijail.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libminijail.so \
	$(LOCAL_PATH)/vndk-26-arm32/libminikin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libminikin.so \
	$(LOCAL_PATH)/vndk-26-arm32/libnativebridge.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libnativebridge.so \
	$(LOCAL_PATH)/vndk-26-arm32/libnativehelper.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libnativehelper.so \
	$(LOCAL_PATH)/vndk-26-arm32/libnativeloader.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libnativeloader.so \
	$(LOCAL_PATH)/vndk-26-arm32/libnativewindow.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libnativewindow.so \
	$(LOCAL_PATH)/vndk-26-arm32/libnetutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libnetutils.so \
	$(LOCAL_PATH)/vndk-26-arm32/libnl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libnl.so \
	$(LOCAL_PATH)/vndk-26-arm32/libopus.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libopus.so \
	$(LOCAL_PATH)/vndk-26-arm32/libpackagelistparser.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libpackagelistparser.so \
	$(LOCAL_PATH)/vndk-26-arm32/libpagemap.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libpagemap.so \
	$(LOCAL_PATH)/vndk-26-arm32/libpcre2.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libpcre2.so \
	$(LOCAL_PATH)/vndk-26-arm32/libpdfium.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libpdfium.so \
	$(LOCAL_PATH)/vndk-26-arm32/libpiex.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libpiex.so \
	$(LOCAL_PATH)/vndk-26-arm32/libpng.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libpng.so \
	$(LOCAL_PATH)/vndk-26-arm32/libpowermanager.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libpowermanager.so \
	$(LOCAL_PATH)/vndk-26-arm32/libpower.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libpower.so \
	$(LOCAL_PATH)/vndk-26-arm32/libprocessgroup.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libprocessgroup.so \
	$(LOCAL_PATH)/vndk-26-arm32/libprocinfo.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libprocinfo.so \
	$(LOCAL_PATH)/vndk-26-arm32/libprotobuf-cpp-full.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libprotobuf-cpp-full.so \
	$(LOCAL_PATH)/vndk-26-arm32/libprotobuf-cpp-lite.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libprotobuf-cpp-lite.so \
	$(LOCAL_PATH)/vndk-26-arm32/libradio_metadata.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libradio_metadata.so \
	$(LOCAL_PATH)/vndk-26-arm32/libradio.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libradio.so \
	$(LOCAL_PATH)/vndk-26-arm32/librilutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/librilutils.so \
	$(LOCAL_PATH)/vndk-26-arm32/libRScpp.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libRScpp.so \
	$(LOCAL_PATH)/vndk-26-arm32/libselinux.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libselinux.so \
	$(LOCAL_PATH)/vndk-26-arm32/libsensor.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libsensor.so \
	$(LOCAL_PATH)/vndk-26-arm32/libskia.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libskia.so \
	$(LOCAL_PATH)/vndk-26-arm32/libsoftkeymasterdevice.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libsoftkeymasterdevice.so \
	$(LOCAL_PATH)/vndk-26-arm32/libsoftkeymaster.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libsoftkeymaster.so \
	$(LOCAL_PATH)/vndk-26-arm32/libsonivox.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libsonivox.so \
	$(LOCAL_PATH)/vndk-26-arm32/libsoundtrigger.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libsoundtrigger.so \
	$(LOCAL_PATH)/vndk-26-arm32/libsparse.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libsparse.so \
	$(LOCAL_PATH)/vndk-26-arm32/libspeexresampler.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libspeexresampler.so \
	$(LOCAL_PATH)/vndk-26-arm32/libsqlite.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libsqlite.so \
	$(LOCAL_PATH)/vndk-26-arm32/libssl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libssl.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_amrnb_common.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_amrnb_common.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_enc_common.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_enc_common.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_foundation.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_foundation.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_omx.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_omx.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_aacdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_aacdec.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_aacenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_aacenc.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_amrdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_amrdec.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_amrnbenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_amrnbenc.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_amrwbenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_amrwbenc.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_avcdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_avcdec.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_avcenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_avcenc.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_flacenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_flacenc.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_g711dec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_g711dec.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_gsmdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_gsmdec.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_hevcdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_hevcdec.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_mp3dec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_mp3dec.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_mpeg2dec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_mpeg2dec.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_mpeg4dec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_mpeg4dec.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_mpeg4enc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_mpeg4enc.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_opusdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_opusdec.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_rawdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_rawdec.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_vorbisdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_vorbisdec.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_vpxdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_vpxdec.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_soft_vpxenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_soft_vpxenc.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstagefright_xmlparser@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstagefright_xmlparser@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm32/libstdc++.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libstdc++.so \
	$(LOCAL_PATH)/vndk-26-arm32/libsuspend.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libsuspend.so \
	$(LOCAL_PATH)/vndk-26-arm32/libsysutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libsysutils.so \
	$(LOCAL_PATH)/vndk-26-arm32/libtinyalsa.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libtinyalsa.so \
	$(LOCAL_PATH)/vndk-26-arm32/libtinyxml2.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libtinyxml2.so \
	$(LOCAL_PATH)/vndk-26-arm32/libui.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libui.so \
	$(LOCAL_PATH)/vndk-26-arm32/libusbhost.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libusbhost.so \
	$(LOCAL_PATH)/vndk-26-arm32/libutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libutils.so \
	$(LOCAL_PATH)/vndk-26-arm32/libvintf.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libvintf.so \
	$(LOCAL_PATH)/vndk-26-arm32/libvixl-arm64.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libvixl-arm64.so \
	$(LOCAL_PATH)/vndk-26-arm32/libvixl-arm.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libvixl-arm.so \
	$(LOCAL_PATH)/vndk-26-arm32/libvorbisidec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libvorbisidec.so \
	$(LOCAL_PATH)/vndk-26-arm32/libvulkan.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libvulkan.so \
	$(LOCAL_PATH)/vndk-26-arm32/libwifi-service.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libwifi-service.so \
	$(LOCAL_PATH)/vndk-26-arm32/libwifi-system.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libwifi-system.so \
	$(LOCAL_PATH)/vndk-26-arm32/libxml2.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libxml2.so \
	$(LOCAL_PATH)/vndk-26-arm32/libyuv.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libyuv.so \
	$(LOCAL_PATH)/vndk-26-arm32/libziparchive.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libziparchive.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/android.hardware.graphics.mapper@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/android.hardware.graphics.mapper@2.0.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/hw/android.hidl.memory@1.0-impl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/hw/android.hidl.memory@1.0-impl.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libutils.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libbcinfo.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libbcinfo.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libhidltransport.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libhidltransport.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libbase.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libbase.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libpng.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libpng.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libbacktrace.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libbacktrace.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/android.hardware.renderscript@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/android.hardware.renderscript@1.0.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libRS_internal.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libRS_internal.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/android.hidl.memory@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/android.hidl.memory@1.0.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/android.hardware.graphics.allocator@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/android.hardware.graphics.allocator@2.0.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libhwbinder.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libhwbinder.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libion.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libion.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libc++.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libc++.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libcutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libcutils.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libRSDriver.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libRSDriver.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libblas.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libblas.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libhidlbase.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libhidlbase.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/android.hardware.graphics.common@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/android.hardware.graphics.common@1.0.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libhardware.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libhardware.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libRSCpuRef.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libRSCpuRef.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/liblzma.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/liblzma.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libcompiler_rt.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libcompiler_rt.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libhidlmemory.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libhidlmemory.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libunwind.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libunwind.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/android.hidl.base@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/android.hidl.base@1.0.so \
	$(LOCAL_PATH)/vndk-sp-26-arm32/libft2.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libft2.so \
	$(LOCAL_PATH)/vndk-27-arm32/libandroidfw.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libandroidfw.so \
	$(LOCAL_PATH)/vndk-27-arm32/libandroid_runtime.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libandroid_runtime.so \
	$(LOCAL_PATH)/vndk-27-arm32/libandroid.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libandroid.so \
	$(LOCAL_PATH)/vndk-27-arm32/libappfuse.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libappfuse.so \
	$(LOCAL_PATH)/vndk-27-arm32/libaudioclient.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libaudioclient.so \
	$(LOCAL_PATH)/vndk-27-arm32/libaudiomanager.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libaudiomanager.so \
	$(LOCAL_PATH)/vndk-27-arm32/libaudiospdif.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libaudiospdif.so \
	$(LOCAL_PATH)/vndk-27-arm32/libcamera_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libcamera_client.so \
	$(LOCAL_PATH)/vndk-27-arm32/libdebuggerd_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libdebuggerd_client.so \
	$(LOCAL_PATH)/vndk-27-arm32/libdng_sdk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libdng_sdk.so \
	$(LOCAL_PATH)/vndk-27-arm32/libdrmframework.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libdrmframework.so \
	$(LOCAL_PATH)/vndk-27-arm32/libeffectsconfig.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libeffectsconfig.so \
	$(LOCAL_PATH)/vndk-27-arm32/libEGL.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libEGL.so \
	$(LOCAL_PATH)/vndk-27-arm32/libETC1.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libETC1.so \
	$(LOCAL_PATH)/vndk-27-arm32/libGLESv2.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libGLESv2.so \
	$(LOCAL_PATH)/vndk-27-arm32/libGLESv3.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libGLESv3.so \
	$(LOCAL_PATH)/vndk-27-arm32/libgraphicsenv.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libgraphicsenv.so \
	$(LOCAL_PATH)/vndk-27-arm32/libharfbuzz_ng.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libharfbuzz_ng.so \
	$(LOCAL_PATH)/vndk-27-arm32/libheif.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libheif.so \
	$(LOCAL_PATH)/vndk-27-arm32/libhwui.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libhwui.so \
	$(LOCAL_PATH)/vndk-27-arm32/libicui18n.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libicui18n.so \
	$(LOCAL_PATH)/vndk-27-arm32/libicuuc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libicuuc.so \
	$(LOCAL_PATH)/vndk-27-arm32/libimg_utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libimg_utils.so \
	$(LOCAL_PATH)/vndk-27-arm32/libinput.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libinput.so \
	$(LOCAL_PATH)/vndk-27-arm32/libjavacore.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libjavacore.so \
	$(LOCAL_PATH)/vndk-27-arm32/libjnigraphics.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libjnigraphics.so \
	$(LOCAL_PATH)/vndk-27-arm32/libkeystore_binder.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libkeystore_binder.so \
	$(LOCAL_PATH)/vndk-27-arm32/liblogwrap.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/liblogwrap.so \
	$(LOCAL_PATH)/vndk-27-arm32/libmediadrm.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libmediadrm.so \
	$(LOCAL_PATH)/vndk-27-arm32/libmediametrics.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libmediametrics.so \
	$(LOCAL_PATH)/vndk-27-arm32/libmedia.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libmedia.so \
	$(LOCAL_PATH)/vndk-27-arm32/libmediautils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libmediautils.so \
	$(LOCAL_PATH)/vndk-27-arm32/libmemunreachable.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libmemunreachable.so \
	$(LOCAL_PATH)/vndk-27-arm32/libminikin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libminikin.so \
	$(LOCAL_PATH)/vndk-27-arm32/libnativebridge.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libnativebridge.so \
	$(LOCAL_PATH)/vndk-27-arm32/libnativehelper.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libnativehelper.so \
	$(LOCAL_PATH)/vndk-27-arm32/libnativeloader.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libnativeloader.so \
	$(LOCAL_PATH)/vndk-27-arm32/libnetd_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libnetd_client.so \
	$(LOCAL_PATH)/vndk-27-arm32/libpackagelistparser.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libpackagelistparser.so \
	$(LOCAL_PATH)/vndk-27-arm32/libpdfium.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libpdfium.so \
	$(LOCAL_PATH)/vndk-27-arm32/libpowermanager.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libpowermanager.so \
	$(LOCAL_PATH)/vndk-27-arm32/libprocessgroup.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libprocessgroup.so \
	$(LOCAL_PATH)/vndk-27-arm32/libRScpp.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libRScpp.so \
	$(LOCAL_PATH)/vndk-27-arm32/libselinux.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libselinux.so \
	$(LOCAL_PATH)/vndk-27-arm32/libsensorservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libsensorservice.so \
	$(LOCAL_PATH)/vndk-27-arm32/libsensor.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libsensor.so \
	$(LOCAL_PATH)/vndk-27-arm32/libskia.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libskia.so \
	$(LOCAL_PATH)/vndk-27-arm32/libsoftkeymaster.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libsoftkeymaster.so \
	$(LOCAL_PATH)/vndk-27-arm32/libsonivox.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libsonivox.so \
	$(LOCAL_PATH)/vndk-27-arm32/libsoundtrigger.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libsoundtrigger.so \
	$(LOCAL_PATH)/vndk-27-arm32/libsparse.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libsparse.so \
	$(LOCAL_PATH)/vndk-27-arm32/libstagefright.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libstagefright.so \
	$(LOCAL_PATH)/vndk-27-arm32/libstdc++.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libstdc++.so \
	$(LOCAL_PATH)/vndk-27-arm32/libvintf.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libvintf.so \
	$(LOCAL_PATH)/vndk-27-arm32/libvulkan.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libvulkan.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.frameworks.displayservice@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.frameworks.displayservice@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.frameworks.schedulerservice@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.frameworks.schedulerservice@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.frameworks.sensorservice@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.frameworks.sensorservice@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.frameworks.vr.composer@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.frameworks.vr.composer@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.audio@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.audio@2.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.audio.common@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.audio.common@2.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.audio.common@2.0-util.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.audio.common@2.0-util.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.audio.effect@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.audio.effect@2.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.automotive.evs@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.automotive.evs@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.automotive.vehicle@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.automotive.vehicle@2.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.biometrics.fingerprint@2.1.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.biometrics.fingerprint@2.1.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.bluetooth@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.bluetooth@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.boot@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.boot@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.broadcastradio@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.broadcastradio@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.broadcastradio@1.1.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.broadcastradio@1.1.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.camera.common@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.camera.common@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.camera.device@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.camera.device@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.camera.device@3.2.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.camera.device@3.2.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.camera.metadata@3.2.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.camera.metadata@3.2.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.camera.provider@2.4.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.camera.provider@2.4.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.configstore@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.configstore@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.configstore-utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.configstore-utils.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.contexthub@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.contexthub@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.drm@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.drm@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.dumpstate@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.dumpstate@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.gatekeeper@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.gatekeeper@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.gnss@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.gnss@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.graphics.allocator@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.graphics.allocator@2.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.graphics.bufferqueue@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.graphics.bufferqueue@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.graphics.composer@2.1.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.graphics.composer@2.1.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.health@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.health@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.ir@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.ir@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.keymaster@3.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.keymaster@3.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.light@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.light@2.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.media@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.media@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.media.omx@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.media.omx@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.memtrack@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.memtrack@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.nfc@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.nfc@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.power@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.power@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.radio@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.radio@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.radio.deprecated@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.radio.deprecated@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.sensors@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.sensors@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.soundtrigger@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.soundtrigger@2.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.tetheroffload.config@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.tetheroffload.config@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.tetheroffload.control@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.tetheroffload.control@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.thermal@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.thermal@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.tv.cec@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.tv.cec@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.tv.input@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.tv.input@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.usb@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.usb@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.vibrator@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.vibrator@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.vr@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.vr@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.wifi@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.wifi@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hardware.wifi.supplicant@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hardware.wifi.supplicant@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hidl.allocator@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hidl.allocator@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hidl.base@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hidl.base@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hidl.token@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hidl.token@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.hidl.token@1.0-utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.hidl.token@1.0-utils.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.system.net.netd@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.system.net.netd@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/android.system.wifi.keystore@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/android.system.wifi.keystore@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/libandroidfw.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libandroidfw.so \
	$(LOCAL_PATH)/vndk-26-arm64/libandroid_runtime.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libandroid_runtime.so \
	$(LOCAL_PATH)/vndk-26-arm64/libandroid.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libandroid.so \
	$(LOCAL_PATH)/vndk-26-arm64/libappfuse.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libappfuse.so \
	$(LOCAL_PATH)/vndk-26-arm64/libaudioclient.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libaudioclient.so \
	$(LOCAL_PATH)/vndk-26-arm64/libaudiomanager.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libaudiomanager.so \
	$(LOCAL_PATH)/vndk-26-arm64/libaudioroute.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libaudioroute.so \
	$(LOCAL_PATH)/vndk-26-arm64/libaudioutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libaudioutils.so \
	$(LOCAL_PATH)/vndk-26-arm64/libavservices_minijail.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libavservices_minijail.so \
	$(LOCAL_PATH)/vndk-26-arm64/libbinder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libbinder.so \
	$(LOCAL_PATH)/vndk-26-arm64/libcamera2ndk.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libcamera2ndk.so \
	$(LOCAL_PATH)/vndk-26-arm64/libcamera_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libcamera_client.so \
	$(LOCAL_PATH)/vndk-26-arm64/libcamera_metadata.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libcamera_metadata.so \
	$(LOCAL_PATH)/vndk-26-arm64/libcameraservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libcameraservice.so \
	$(LOCAL_PATH)/vndk-26-arm64/libcap.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libcap.so \
	$(LOCAL_PATH)/vndk-26-arm64/libcrypto.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libcrypto.so \
	$(LOCAL_PATH)/vndk-26-arm64/libcrypto_utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libcrypto_utils.so \
	$(LOCAL_PATH)/vndk-26-arm64/libcurl.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libcurl.so \
	$(LOCAL_PATH)/vndk-26-arm64/libdebuggerd_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libdebuggerd_client.so \
	$(LOCAL_PATH)/vndk-26-arm64/libdiskconfig.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libdiskconfig.so \
	$(LOCAL_PATH)/vndk-26-arm64/libdng_sdk.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libdng_sdk.so \
	$(LOCAL_PATH)/vndk-26-arm64/libdumpstateutil.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libdumpstateutil.so \
	$(LOCAL_PATH)/vndk-26-arm64/libEGL.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libEGL.so \
	$(LOCAL_PATH)/vndk-26-arm64/libETC1.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libETC1.so \
	$(LOCAL_PATH)/vndk-26-arm64/libevent.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libevent.so \
	$(LOCAL_PATH)/vndk-26-arm64/libexif.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libexif.so \
	$(LOCAL_PATH)/vndk-26-arm64/libexpat.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libexpat.so \
	$(LOCAL_PATH)/vndk-26-arm64/libfmq.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libfmq.so \
	$(LOCAL_PATH)/vndk-26-arm64/libgatekeeper.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libgatekeeper.so \
	$(LOCAL_PATH)/vndk-26-arm64/libgui.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libgui.so \
	$(LOCAL_PATH)/vndk-26-arm64/libhardware_legacy.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libhardware_legacy.so \
	$(LOCAL_PATH)/vndk-26-arm64/libharfbuzz_ng.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libharfbuzz_ng.so \
	$(LOCAL_PATH)/vndk-26-arm64/libhwui.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libhwui.so \
	$(LOCAL_PATH)/vndk-26-arm64/libicui18n.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libicui18n.so \
	$(LOCAL_PATH)/vndk-26-arm64/libicuuc.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libicuuc.so \
	$(LOCAL_PATH)/vndk-26-arm64/libimg_utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libimg_utils.so \
	$(LOCAL_PATH)/vndk-26-arm64/libinput.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libinput.so \
	$(LOCAL_PATH)/vndk-26-arm64/libjavacore.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libjavacore.so \
	$(LOCAL_PATH)/vndk-26-arm64/libjnigraphics.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libjnigraphics.so \
	$(LOCAL_PATH)/vndk-26-arm64/libjpeg.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libjpeg.so \
	$(LOCAL_PATH)/vndk-26-arm64/libkeymaster1.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libkeymaster1.so \
	$(LOCAL_PATH)/vndk-26-arm64/libkeymaster_messages.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libkeymaster_messages.so \
	$(LOCAL_PATH)/vndk-26-arm64/libkeystore_binder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libkeystore_binder.so \
	$(LOCAL_PATH)/vndk-26-arm64/libldacBT_abr.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libldacBT_abr.so \
	$(LOCAL_PATH)/vndk-26-arm64/libldacBT_enc.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libldacBT_enc.so \
	$(LOCAL_PATH)/vndk-26-arm64/liblz4.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/liblz4.so \
	$(LOCAL_PATH)/vndk-26-arm64/libmediadrm.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libmediadrm.so \
	$(LOCAL_PATH)/vndk-26-arm64/libmedia_helper.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libmedia_helper.so \
	$(LOCAL_PATH)/vndk-26-arm64/libmediametrics.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libmediametrics.so \
	$(LOCAL_PATH)/vndk-26-arm64/libmedia.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libmedia.so \
	$(LOCAL_PATH)/vndk-26-arm64/libmediautils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libmediautils.so \
	$(LOCAL_PATH)/vndk-26-arm64/libmemtrack.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libmemtrack.so \
	$(LOCAL_PATH)/vndk-26-arm64/libmemunreachable.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libmemunreachable.so \
	$(LOCAL_PATH)/vndk-26-arm64/libminijail.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libminijail.so \
	$(LOCAL_PATH)/vndk-26-arm64/libminikin.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libminikin.so \
	$(LOCAL_PATH)/vndk-26-arm64/libnativebridge.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libnativebridge.so \
	$(LOCAL_PATH)/vndk-26-arm64/libnativehelper.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libnativehelper.so \
	$(LOCAL_PATH)/vndk-26-arm64/libnativeloader.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libnativeloader.so \
	$(LOCAL_PATH)/vndk-26-arm64/libnativewindow.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libnativewindow.so \
	$(LOCAL_PATH)/vndk-26-arm64/libnetutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libnetutils.so \
	$(LOCAL_PATH)/vndk-26-arm64/libnl.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libnl.so \
	$(LOCAL_PATH)/vndk-26-arm64/libopus.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libopus.so \
	$(LOCAL_PATH)/vndk-26-arm64/libpackagelistparser.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libpackagelistparser.so \
	$(LOCAL_PATH)/vndk-26-arm64/libpagemap.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libpagemap.so \
	$(LOCAL_PATH)/vndk-26-arm64/libpcre2.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libpcre2.so \
	$(LOCAL_PATH)/vndk-26-arm64/libpdfium.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libpdfium.so \
	$(LOCAL_PATH)/vndk-26-arm64/libpiex.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libpiex.so \
	$(LOCAL_PATH)/vndk-26-arm64/libpng.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libpng.so \
	$(LOCAL_PATH)/vndk-26-arm64/libpowermanager.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libpowermanager.so \
	$(LOCAL_PATH)/vndk-26-arm64/libpower.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libpower.so \
	$(LOCAL_PATH)/vndk-26-arm64/libprocessgroup.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libprocessgroup.so \
	$(LOCAL_PATH)/vndk-26-arm64/libprocinfo.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libprocinfo.so \
	$(LOCAL_PATH)/vndk-26-arm64/libprotobuf-cpp-full.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libprotobuf-cpp-full.so \
	$(LOCAL_PATH)/vndk-26-arm64/libprotobuf-cpp-lite.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libprotobuf-cpp-lite.so \
	$(LOCAL_PATH)/vndk-26-arm64/libradio_metadata.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libradio_metadata.so \
	$(LOCAL_PATH)/vndk-26-arm64/libradio.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libradio.so \
	$(LOCAL_PATH)/vndk-26-arm64/librilutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/librilutils.so \
	$(LOCAL_PATH)/vndk-26-arm64/libRScpp.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libRScpp.so \
	$(LOCAL_PATH)/vndk-26-arm64/libselinux.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libselinux.so \
	$(LOCAL_PATH)/vndk-26-arm64/libsensor.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libsensor.so \
	$(LOCAL_PATH)/vndk-26-arm64/libskia.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libskia.so \
	$(LOCAL_PATH)/vndk-26-arm64/libsoftkeymasterdevice.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libsoftkeymasterdevice.so \
	$(LOCAL_PATH)/vndk-26-arm64/libsoftkeymaster.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libsoftkeymaster.so \
	$(LOCAL_PATH)/vndk-26-arm64/libsonivox.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libsonivox.so \
	$(LOCAL_PATH)/vndk-26-arm64/libsoundtrigger.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libsoundtrigger.so \
	$(LOCAL_PATH)/vndk-26-arm64/libsparse.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libsparse.so \
	$(LOCAL_PATH)/vndk-26-arm64/libspeexresampler.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libspeexresampler.so \
	$(LOCAL_PATH)/vndk-26-arm64/libsqlite.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libsqlite.so \
	$(LOCAL_PATH)/vndk-26-arm64/libssl.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libssl.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_amrnb_common.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_amrnb_common.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_enc_common.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_enc_common.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_foundation.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_foundation.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_omx.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_omx.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_aacdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_aacdec.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_aacenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_aacenc.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_amrdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_amrdec.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_amrnbenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_amrnbenc.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_amrwbenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_amrwbenc.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_avcdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_avcdec.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_avcenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_avcenc.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_flacenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_flacenc.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_g711dec.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_g711dec.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_gsmdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_gsmdec.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_hevcdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_hevcdec.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_mp3dec.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_mp3dec.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_mpeg2dec.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_mpeg2dec.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_mpeg4dec.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_mpeg4dec.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_mpeg4enc.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_mpeg4enc.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_opusdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_opusdec.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_rawdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_rawdec.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_vorbisdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_vorbisdec.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_vpxdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_vpxdec.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_soft_vpxenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_soft_vpxenc.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstagefright_xmlparser@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstagefright_xmlparser@1.0.so \
	$(LOCAL_PATH)/vndk-26-arm64/libstdc++.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libstdc++.so \
	$(LOCAL_PATH)/vndk-26-arm64/libsuspend.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libsuspend.so \
	$(LOCAL_PATH)/vndk-26-arm64/libsysutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libsysutils.so \
	$(LOCAL_PATH)/vndk-26-arm64/libtinyalsa.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libtinyalsa.so \
	$(LOCAL_PATH)/vndk-26-arm64/libtinyxml2.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libtinyxml2.so \
	$(LOCAL_PATH)/vndk-26-arm64/libui.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libui.so \
	$(LOCAL_PATH)/vndk-26-arm64/libusbhost.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libusbhost.so \
	$(LOCAL_PATH)/vndk-26-arm64/libutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libutils.so \
	$(LOCAL_PATH)/vndk-26-arm64/libvintf.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libvintf.so \
	$(LOCAL_PATH)/vndk-26-arm64/libvixl-arm64.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libvixl-arm64.so \
	$(LOCAL_PATH)/vndk-26-arm64/libvixl-arm.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libvixl-arm.so \
	$(LOCAL_PATH)/vndk-26-arm64/libvorbisidec.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libvorbisidec.so \
	$(LOCAL_PATH)/vndk-26-arm64/libvulkan.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libvulkan.so \
	$(LOCAL_PATH)/vndk-26-arm64/libwifi-service.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libwifi-service.so \
	$(LOCAL_PATH)/vndk-26-arm64/libwifi-system.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libwifi-system.so \
	$(LOCAL_PATH)/vndk-26-arm64/libxml2.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libxml2.so \
	$(LOCAL_PATH)/vndk-26-arm64/libyuv.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libyuv.so \
	$(LOCAL_PATH)/vndk-26-arm64/libziparchive.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-26/libziparchive.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/android.hardware.graphics.mapper@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/android.hardware.graphics.mapper@2.0.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/hw/android.hidl.memory@1.0-impl.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/hw/android.hidl.memory@1.0-impl.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libutils.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libbcinfo.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libbcinfo.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libhidltransport.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libhidltransport.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libbase.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libbase.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libpng.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libpng.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libbacktrace.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libbacktrace.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/android.hardware.renderscript@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/android.hardware.renderscript@1.0.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libRS_internal.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libRS_internal.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/android.hidl.memory@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/android.hidl.memory@1.0.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/android.hardware.graphics.allocator@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/android.hardware.graphics.allocator@2.0.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libhwbinder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libhwbinder.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libion.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libion.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libc++.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libc++.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libcutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libcutils.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libRSDriver.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libRSDriver.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libblas.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libblas.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libhidlbase.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libhidlbase.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/android.hardware.graphics.common@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/android.hardware.graphics.common@1.0.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libhardware.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libhardware.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libRSCpuRef.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libRSCpuRef.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/liblzma.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/liblzma.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libcompiler_rt.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libcompiler_rt.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libhidlmemory.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libhidlmemory.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libunwind.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libunwind.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/android.hidl.base@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/android.hidl.base@1.0.so \
	$(LOCAL_PATH)/vndk-sp-26-arm64/libft2.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-sp-26/libft2.so \
	$(LOCAL_PATH)/vndk-27-arm64/libandroidfw.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libandroidfw.so \
	$(LOCAL_PATH)/vndk-27-arm64/libandroid_runtime.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libandroid_runtime.so \
	$(LOCAL_PATH)/vndk-27-arm64/libandroid.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libandroid.so \
	$(LOCAL_PATH)/vndk-27-arm64/libappfuse.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libappfuse.so \
	$(LOCAL_PATH)/vndk-27-arm64/libaudioclient.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libaudioclient.so \
	$(LOCAL_PATH)/vndk-27-arm64/libaudiomanager.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libaudiomanager.so \
	$(LOCAL_PATH)/vndk-27-arm64/libaudiospdif.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libaudiospdif.so \
	$(LOCAL_PATH)/vndk-27-arm64/libcamera_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libcamera_client.so \
	$(LOCAL_PATH)/vndk-27-arm64/libdebuggerd_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libdebuggerd_client.so \
	$(LOCAL_PATH)/vndk-27-arm64/libdng_sdk.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libdng_sdk.so \
	$(LOCAL_PATH)/vndk-27-arm64/libdrmframework.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libdrmframework.so \
	$(LOCAL_PATH)/vndk-27-arm64/libeffectsconfig.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libeffectsconfig.so \
	$(LOCAL_PATH)/vndk-27-arm64/libEGL.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libEGL.so \
	$(LOCAL_PATH)/vndk-27-arm64/libETC1.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libETC1.so \
	$(LOCAL_PATH)/vndk-27-arm64/libGLESv2.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libGLESv2.so \
	$(LOCAL_PATH)/vndk-27-arm64/libGLESv3.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libGLESv3.so \
	$(LOCAL_PATH)/vndk-27-arm64/libgraphicsenv.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libgraphicsenv.so \
	$(LOCAL_PATH)/vndk-27-arm64/libharfbuzz_ng.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libharfbuzz_ng.so \
	$(LOCAL_PATH)/vndk-27-arm64/libheif.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libheif.so \
	$(LOCAL_PATH)/vndk-27-arm64/libhwui.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libhwui.so \
	$(LOCAL_PATH)/vndk-27-arm64/libicui18n.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libicui18n.so \
	$(LOCAL_PATH)/vndk-27-arm64/libicuuc.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libicuuc.so \
	$(LOCAL_PATH)/vndk-27-arm64/libimg_utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libimg_utils.so \
	$(LOCAL_PATH)/vndk-27-arm64/libinput.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libinput.so \
	$(LOCAL_PATH)/vndk-27-arm64/libjavacore.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libjavacore.so \
	$(LOCAL_PATH)/vndk-27-arm64/libjnigraphics.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libjnigraphics.so \
	$(LOCAL_PATH)/vndk-27-arm64/libkeystore_binder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libkeystore_binder.so \
	$(LOCAL_PATH)/vndk-27-arm64/liblogwrap.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/liblogwrap.so \
	$(LOCAL_PATH)/vndk-27-arm64/libmediadrm.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libmediadrm.so \
	$(LOCAL_PATH)/vndk-27-arm64/libmediametrics.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libmediametrics.so \
	$(LOCAL_PATH)/vndk-27-arm64/libmedia.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libmedia.so \
	$(LOCAL_PATH)/vndk-27-arm64/libmediautils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libmediautils.so \
	$(LOCAL_PATH)/vndk-27-arm64/libmemunreachable.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libmemunreachable.so \
	$(LOCAL_PATH)/vndk-27-arm64/libminikin.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libminikin.so \
	$(LOCAL_PATH)/vndk-27-arm64/libnativebridge.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libnativebridge.so \
	$(LOCAL_PATH)/vndk-27-arm64/libnativehelper.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libnativehelper.so \
	$(LOCAL_PATH)/vndk-27-arm64/libnativeloader.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libnativeloader.so \
	$(LOCAL_PATH)/vndk-27-arm64/libnetd_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libnetd_client.so \
	$(LOCAL_PATH)/vndk-27-arm64/libpackagelistparser.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libpackagelistparser.so \
	$(LOCAL_PATH)/vndk-27-arm64/libpdfium.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libpdfium.so \
	$(LOCAL_PATH)/vndk-27-arm64/libpowermanager.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libpowermanager.so \
	$(LOCAL_PATH)/vndk-27-arm64/libprocessgroup.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libprocessgroup.so \
	$(LOCAL_PATH)/vndk-27-arm64/libRScpp.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libRScpp.so \
	$(LOCAL_PATH)/vndk-27-arm64/libselinux.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libselinux.so \
	$(LOCAL_PATH)/vndk-27-arm64/libsensorservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libsensorservice.so \
	$(LOCAL_PATH)/vndk-27-arm64/libsensor.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libsensor.so \
	$(LOCAL_PATH)/vndk-27-arm64/libskia.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libskia.so \
	$(LOCAL_PATH)/vndk-27-arm64/libsoftkeymaster.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libsoftkeymaster.so \
	$(LOCAL_PATH)/vndk-27-arm64/libsonivox.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libsonivox.so \
	$(LOCAL_PATH)/vndk-27-arm64/libsoundtrigger.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libsoundtrigger.so \
	$(LOCAL_PATH)/vndk-27-arm64/libsparse.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libsparse.so \
	$(LOCAL_PATH)/vndk-27-arm64/libstagefright.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libstagefright.so \
	$(LOCAL_PATH)/vndk-27-arm64/libstdc++.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libstdc++.so \
	$(LOCAL_PATH)/vndk-27-arm64/libvintf.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libvintf.so \
	$(LOCAL_PATH)/vndk-27-arm64/libvulkan.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libvulkan.so \
	$(LOCAL_PATH)/vndk/vndk-26-arm32-binder32/libbinder.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-26/libbinder.so \
        $(LOCAL_PATH)/vndk/vndk-26-arm32-binder32/libhwbinder.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-sp-26/libhwbinder.so
